services:
  sofa-qtcreator:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /trunet/data/volume1/src:/home/user/src
      - /trunet/data/volume1/build:/home/user/build
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
