networks:
  sofa-ros-local-network:
    driver: bridge
    ipam:
      config:
      - gateway: 10.8.0.1
        subnet: 10.8.0.0/16
services:
  qt-creator:
    build:
      args:
        CMAKE_BUILD_TYPE: Debug
        ROS_MASTER_URI: http://ros-moveit:11311
        USER: fabian
      context: .
      dockerfile: qt.Dockerfile
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - DISPLAY=:0
    - QT_X11_NO_MITSHM=1
    - ROS_MASTER_URI=http://10.8.0.2:11311
    hostname: sofa-ros
    networks:
      sofa-ros-local-network:
        aliases:
        - sofa-ros
        ipv4_address: 10.8.0.3
    security_opt:
    - seccomp:unconfined
    stdin_open: true
    tty: true
    volumes:
    - ./home/fabian:/home/fabian
    - /trunet/data/volume1/build:/home/fabian/build
    - /trunet/data/volume1/src:/home/fabian/src
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - nvidia_driver_390.30:/usr/local/nvidia:ro
  ros-moveit:
    build:
      args:
        CMAKE_BUILD_TYPE: Debug
        NRP_USER: fabian
        ROS_MASTER_URI: http://ros-moveit:11311
      context: .
      dockerfile: ros_moveit.Dockerfile
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - DISPLAY=:0
    - QT_X11_NO_MITSHM=1
    - ROS_MASTER_URI=http://localhost:11311
    hostname: ros-moveit
    networks:
      sofa-ros-local-network:
        aliases:
        - ros-moveit
        ipv4_address: 10.8.0.2
    stdin_open: true
    tty: true
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - nvidia_driver_390.30:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_390.30:
    external: true
